# Generated by Django 5.1.2 on 2024-11-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driver',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
